spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc  # change this to your own jdbc url
    username: sustcadmin  # change this to your own username (avoid using a superuser)
    password: sustcpwd  # change this to your own password

logging:
  level:
    root: off
    io.sustc: debug

logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: small_data
  student-mode: true
